/// !@! uint256,uint256,uint256,string memory !@!

//
//    /$$    /$$$$$$$$ /$$$$$$    /$$
//   | $$   |_____ $$//$$__  $$ /$$$$
//  /$$$$$$      /$$/|__/  \ $$|_  $$
// |_  $$_/     /$$/   /$$$$$$/  | $$
//   | $$      /$$/   /$$____/   | $$
//   | $$ /$$ /$$/   | $$        | $$
//   |  $$$$//$$/    | $$$$$$$$ /$$$$$$
//    \___/ |__/     |________/|______/
//  t721: 0.1.0, sol: 0.5.0

/// This contract has been automatically generated by combining the following 3 event plugs
/// MinterPayableFixed Mipafi, build_args: [uint256,uint256,uint256,string memory], action_args: [], t721_version: 0.1.0, solidity_version: 0.5.0
/// MarketerDisabled Madi, build_args: [], action_args: [], t721_version: 0.1.0, solidity_version: 0.5.0
/// ApproverTester Apte, build_args: [], action_args: [], t721_version: 0.1.0, solidity_version: 0.5.0

pragma solidity 0.5.0;

import "zos-lib/contracts/Initializable.sol";

import "../minters/MinterPayableFixed.sol";
import "../marketers/MarketerDisabled.sol";
import "../approvers/ApproverTester.sol";

contract EventV0_Mipafi_Madi_Apte is Initializable, MinterPayableFixed, MarketerDisabled, ApproverTester {

    address private t721;
    string private _uri;

    function initialize(address _t721, uint256 arg1, uint256 arg2, uint256 arg3, string memory arg4) public initializer {
        t721 = _t721;
        minter_set_T721(_t721);
        marketer_set_T721(_t721);
        approver_set_T721(_t721);
        configure_minter(arg1,arg2,arg3,arg4);
        configure_marketer();
        configure_approver();
    }

    function supportsInterface(bytes4 _interface) public pure returns (bool) {
        return ((_interface == getMarketerInterfaceSignature())
        || (_interface == getMinterInterfaceSignature())
        || (_interface == getApproverInterfaceSignature()));
    }

}
